 # Clases Machine Learning con Python
 
 <br>
 <img src="ml2.jpg"  width="500" height="300">
 <br>
 
 ### Fernanda Mora
 
 #### Noviembre, 2018
 

## Contenido

- Introducción y herramientas
- Utilidades y tipos de datos
- Numpy
- Basics de Análisis de Datos
- Visualización
- Estructuras de control
- Funciones
- DataFrames
- Ejercicio para entregar
- Referencias

# Introducción y herramientas

## ¿Qué es machine learning?

**¿Qué cambió?**
- Aumento en **datos** (volumen, variedad, velocidad)
- Incremento de mejora en capacidades de computadoras: procesamiento y almacenamiento. Cómputo en la nube, Cómputo distribuido, Programación paralela, bases de datos NoSQL.

**Surgen**
- Mucha riqueza en datos, ¡modelos!
- Modelos que permiten "aprender" rápidamente: ¿cómo los hacemos? antes eran basados en reglas.

**¿Qué es machine learning, pues?**

<img src="whatis.jpg"  width="600" height="700">

- En estadística, el target se llama varibale dependiente. En machine learning **target**
- En machine learning, una variable categórica de estadística se llama **etiqueta**.
- En machine learning, una transformación de estadística se llama *feature creation*

[¿En dónde estamos?](http://houseofbots.com/news-detail/3686-4-how-to-make-a-career-in-these-field-data-science-machine-learning-and-big-data)


### Modelos

Pipeline general para generar conocimiento a través de datos:

<img src="model.jpg"  width="1000" height="500">


Tipos de modelos de machine learning según el problema que abordamos:

 <img src="mlcheatsheet.png"  width="800" height="500">


- Usaremos [scikit-learn](https://scikit-learn.org/stable/)

<img src="model2"  width="800" height="500">



## Datasets
- Actualmente ya hay muchos datasets en la red para trabajar
- Checa [aquí](https://www.kdnuggets.com/datasets/index.html) para encontrar bastantes repositorios internacionales para hacer minería de datos y ciencia de Datos
- Otra opción para datos de finanzas y ecnómicos es [Quandl](https://www.quandl.com/), pero muchos tienen costo
- Para datos mexicanos tenemos  [INEGI](http://www.inegi.org.mx/est/lista_cubos/)
- También tenemos [Datos Gob](https://datos.gob.mx), una plataforma de datos abiertos del gobierno iniciada hace algunos años
- Para las siguientes clases usaremos los del repositorio del curso
- En las siguientes sesiones vamos a ver cómo hacer *scrapping* de la red con R
- Es posible importar datos de bases de datos no relacionales como MongoDB, ver [tutorial](https://statcompute.wordpress.com/2013/06/08/r-and-mongodb/)

## ¿Qué es Python?
- Desarrollado por Guido Van Rossum
- De propósito general: puedes construir lo que quieras
- Open source, es decir, es *gratis*
- Lenguaje orientado a objetos: todo es un objeto
- Es fácil hacer paquetes para Python, también para Ciencia de Datos
- Vamos a ver Python enfocado a Ciencia de Datos
    - Cómo guardar datos
    - Cómo limpiar datos
    - Cómo manipular datos
    - Herramientas para análisis
- Hay muchas versiones de Python, vamos a trabajar con la 3.7
    - Solamente si van a trabajar con [Theano](http://deeplearning.net/software/theano/) recomienda la 2.7


## ¿Cómo vamos a trabajar?
- Bajar [Anaconda](https://www.anaconda.com/)
- Bajar [Jupyter](http://jupyter.org/)
- Bajar [Spyder](https://www.spyder-ide.org/)
- Shell de Python:
    - Es como la consola de R
    - Permite escribir código para experimentar
- Scripts:
    - Son archivos de texto reproducibles, tienen la extensión *.py*
    - Contienen una serie de comandos en Python
    - Similares a escribir en el shell de IPython
- Jupyter Notebook
    - Es un cuaderno que nos permite combinar tanto texto como código
    - El texto está escrito con formato Markdown igual que RMarkdown :)
- Spyder
    - Muy parecido a RStudio pero para Python
    - Es uno de los IDES más populares

### ¿Qué es Anaconda?

- Es una distribución de Python y de R, la más famosa para Ciencia de Datos
- 6 millones de usuarios que hacen ciencia de datos
- Estándar de la industria para desarrollar, probar y entrenar modelos en una sola máquina
- Permite la colaboración de muchos usuarios en tiempo real
- Permite crear ambientes con versiones específicas de Python y paquetes instalados: ENCAPSULAMIENTO
- Esto es un súper plus en Python porque tenemos muchas versiones diferentes que son compatibles con algunos paquetes pero no con otros
- Es fácil crear una seria de paquetes y versiones que sean distribuibles, i.e. que pueda compartir con otros usuarios, incluyendo todas sus dependencias
- Cuando instalamos Anaconda, podemos crear un ambiente y ponerle la versión de Python que queramos
- Anaconda ya tiene precargados el NoteBook de Jupyer y otros paquetes para ciencia de datos

#### Cómo usamos Anaconda

- Creación de [ambientes](https://conda.io/docs/user-guide/tasks/manage-environments.html#activate-env)

1. Para crear un ambiente de cierta versión de Python:

`conda create -n myenv python=3.4`

2. Para instalar un paquete

`conda install -n myenv scipy`
.
    - Si queremos una versión específica del paquete: 
    
  `conda install -n myenv scipy=0.15.0`
     
3. Si queremos instalar de una vez Python con ciertos paquetes

`conda create -n myenv python=3.4 scipy=0.15.0 astroid babel`

4. Si queremos clonar un ambiente:

`conda create --name myclone --clone myenv`

5. Para activar un ambiente

    - Windows: `activate myenv`
    - macOS y Linux: `source activate myenv`
    
6. Desactivar un ambiente:

    - Windows: `deactivate`
    - macOS y Linux: `source deactivate`

7. Para ver listado de ambientes

`conda info --envs`

8. Para saber qué ambiente está corriendo, me fijo en el que tiene el asterisco

`conda info --envs`

9. Para saber qué paquetes tiene instalados un ambiente

`conda list -n myenv`

10. Para saber qué paquetes tiene instalados mi ambiente corriendo

`conda list`

11. Para usar el comando `pip` (para instalar paquetes en Python), usamos:

`conda install -n myenv pip
source activate myenv
pip <pip_subcommand>`

12. Para eliminar un ambiente

`conda remove --name myenv --all`

> **EJERCICIO.** Crear un ambiente con Python 3.7 en Anaconda, instálale el paquete `pip` y finalmente actívalo. Cerciórate que ese nuevo ambiente está instalado.


### ¿Qué es el Notebook de Jupyter?

- [Jupyter Notebook](http://jupyter.org/) es una aplicación web libre que permite crear y compartir documentos con texto,código, ecuaciones, visualizaciones
- Se usa principalmente para hacer ciencia de datos (limpieza, transformación, modelado estadístico, machine learning, simulación, visualización)
- Puedes embeber código, gráficos, urls, videos y texto usando como sintaxis markdown
- Se puede usar con:
    - Python
    - Julia
    - R
    - C++
    - Scala
- Features:
    - Trabaja con varios lenguajes
    - Puedes compartir los notebooks por email, Dropbox, GitHub y el Jupyter Notebook Viewer
    - Output interactivo: HTML, images, videos, LaTeX
    - Integración con herramientas de Big Data de Apache Spark desde Python (Pyspark, la API de Python para Spark),  R  (Sparklyr) y Scala. Es decir, se puede explorar lo mismo con pandas, scikit-learn, ggplot2, Tensorflow
    - Se puede exportar en muchos formatos:
            - html
            - .ipynb (notebook)
            - pdf
            - LaTex
    


#### ¿Cómo instalamos Jupyter?

Para tener *Jupyter*, necesitamos tener Python>=3.3 o Python 2.7

2 maneras:

- Usando *Anaconda*, que ya trae Python y Jupyter 
- Usando `pip`python3 -m pip install --upgrade pip. `pip` es el manejador de paquetes de Python, con ese comando instalaremos los paquetes.

`python3 -m pip install jupyter`


#### ¿Cómo abrimos un notebook de Jupyter?

- Simplemente creamos nuestro ambiente de Python en Anaconda, y escribimos `jupyter notebook`. Se nos abrirá un *Jupyter* con 

- Si no instalamos *Anaconda*, entonces simplemente ponemos `jupyter notebook` en la terminal

- ¿Cómo comparto mi notebook de Python?

#### ¿Cómo corremos los chunks de código en un notebook de Jupyer?

- Una caja de texto o código se corre de varias maneras:
- Individualmente pulsando el botón *Run* o `Shift+Enter`
- Individualmente en el menú *Cell*
- Todas con el menú `Cell` con la opción *Rull all*
- Opciones customizables usando el menú *Cell*

#### ¿Cómo compartimos nuestro notebook de Jupyter?

1. Hostear tu notebook de Python en un repo de Github. Esto tiene la ventaja de que está montado en la red.
    - Ir [NBViewer](http://nbviewer.ipython.org/) y pegar el URL de Github
ó

2. Email ó

3. Dropbox

4. Al parecer aún no se puede hostear en Bitbucket. Se supone que esto es una aplicación para hacerlo: [aplicación](https://bitbucket.org/bitbucket/bitbucket-nbviewer/src/master/)

>**EJERCICIO.** Dentro de tu ambiente de Python que creaste, abre un notebook de Jupyter, escribe tu nombre y expórtalo como Notebook .ipynb. Observa que también puedes ver tus proyectos de R en el mismo notebook de Jupyter pero observa también que todo esto está en ambiente local.

>**EJERCICIO.** Hostea tu Notebook en [NBViewer](http://nbviewer.ipython.org/). Hint: Debes abrir una [cuenta en Github](https://reproducible-science-curriculum.github.io/sharing-RR-Jupyter/01-sharing-github/). Posteriormente sigue estas [instrucciones](https://reproducible-science-curriculum.github.io/sharing-RR-Jupyter/01-sharing-github/)

### ¿Qué es Spyder?
- [Spyder](https://www.spyder-ide.org/) es un IDE (Integrated Development Environment) escrito para trabajar con Python
- Está orientado al cómputo científico
- Es muy parecido a RStudio, así que será sencillo usarlo
- Viene con un editor para escribir código, una consola para evaluar y ver resultados
- También viene con una vista de variables para ver las que se han usado
- Otra opción de editor es [Pycharm](https://www.jetbrains.com/pycharm/), sin embargo esta IDE es mucho más compleja y está más orientada a Desarrolladores

> **EJERCICIO**. Abre Spyder desde la consola, crea un archivo que imprima tu nombre: `print("My nombre es ...")` y córrelo en la consola.


### Resumen

![](software_python.png)

## Utilidades y tipos de datos 

### Preliminares
- Comentarios se escriben con `#`
- Python puede usarse como calculadora:
    - Exponenciación: 2**4
    - Módulo: `5%2`
- Declaración de variables se hacen con `=`
- Ayuda se pide con `help()`. Tres tipos de *ayuda*:
    1. Pasándole el nombre de un objeto: `help(print)`, `help(list)`
    2. Pasándole el nombre de un string (método, función, clase, keyword): `help('def')`
    3. Abriendo una consola interactiva de ayuda de Python: `help()`
    4. Revisando directamente la documentación de [*Scypy*](https://www.scipy.org/docs.html)
    
- Ver en qué versión de Python estás trabajando: `sys.version_info`. Verifica que es la 3.7

In [1]:
help([1, 2, 3])

help("def")

import sys 

print(sys.version_info)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [2]:
print("Así declaramos una variable: ")

x=2

print("\n")
print("Y la imprimimos: ")
print(x)

Así declaramos una variable: 


Y la imprimimos: 
2


### Tipos básicos

- Tipos de datos
    - `int`: enteros
    - `float`: punto flotante, tiene parte entera y decimal separada por punto
    - `str`: strings
    - `bool`: booleanos
- Cada tipo tiene una funcionalidad distinta asociada
- El tipado en Python es *dinámico*, lo cual significa que el tipo de variable no tiene que ser declarado al inicio, pues el tipo de variable se conoce hasta que se corre el código
- Para saber el tipo de variables: `type()`

In [3]:
print("Enteros: ")
type(5)

Enteros: 


int

In [4]:
print("Floats: ")
#float
type(1.10)

Floats: 


float

In [5]:
print("Strings tenemos dos maneras de escribirlos: ")
print("hola")
print('hola')
print(type("hola"))

print("Los tipos de datos se comportan diferente")
"se"+"pega"*10

Strings tenemos dos maneras de escribirlos: 
hola
hola
<class 'str'>
Los tipos de datos se comportan diferente


'sepegapegapegapegapegapegapegapegapegapega'

### Cast
- `int()`
- `float()`
- `bool()`
- `str()`

### Asignación de variables
- La asignación se hace usando `=`
- Es por *referencia*, no por *valor* (recordar que en R es por *valor*)

In [6]:
print("Asigno a x una lista")
x = [1,2,3]
print(x)

print("\n")
print("Ahora guardo en y lo que estaba en x")
y = x

print("\n")
y[0] =100
print("Ahora modifico la primer entrada de y en " + str(y[0]))



print("\n")
print("Imprimo x y me doy cuenta que el valor también cambió")
print("Esto es porque la asignación es por referencia, no por valor")
print(x)

print("\n")
print("Ahora si en vez de lo anterior convierto a lista:")
y=list(x)

y[0]=1000000
print("Vuelvo a modificar la primer entrada de y en " + str(y[0]))
print("ahora 'y' es " + str(y))

print("\n")
print("Pero el valor de x no se modifico, ¿por qué?")

print(x)

Asigno a x una lista
[1, 2, 3]


Ahora guardo en y lo que estaba en x


Ahora modifico la primer entrada de y en 100


Imprimo x y me doy cuenta que el valor también cambió
Esto es porque la asignación es por referencia, no por valor
[100, 2, 3]


Ahora si en vez de lo anterior convierto a lista:
Vuelvo a modificar la primer entrada de y en 1000000
ahora 'y' es [1000000, 2, 3]


Pero el valor de x no se modifico, ¿por qué?
[100, 2, 3]


Si quisiéramos que no se modifique el valor, es decir, hacer **asignación por valor** como hacíamos en R, hacemos:


In [7]:
x = [1,2,3]
y = x[:]
x[0] = 3
print(y)
print(x)

[1, 2, 3]
[3, 2, 3]


### Impresión
- Se hace usando `print()`
- Si se van a imprimir varios tipos de datos, se tiene que hacer *cast* a string antes 

In [8]:
x = 20
print("Hola, tengo " + str(x) + " años")

Hola, tengo 20 años


In [9]:
print(x+30, x, 10)


50 20 10


In [10]:
True+False

1

> **EJERCICIO.** ¿Cómo difiere Python de R con respecto a la forma de imprimir?

### Listas
- Otro tipo de dato
- Sintaxis: `[x, y, z]`
- Colección de valores
- Pueden tener cualquier tipo de dato (incluso listas!)
- Con `len` puedo ver su longitud

In [11]:
my_lista  = ["hola", "tengo", 10, ["años", "y contanto"]]
print(my_lista)
print(len(my_lista))

['hola', 'tengo', 10, ['años', 'y contanto']]
4


#### Acceso a listas:

    - Indexación: se hace usando `[]` al elemento que queremos accesar. 
        - Se empieza por *cero*, es decir `[0]` es el primer elemento
        - Podemos accesar al último elemento usando `[-1]`
    - Rangos: para obtener un subconjunto de la muestra, se hace usando `[inicio: final]`
        - El inicio es inclusivo, el final es exclusivo, es decir, el final no se incluye
    - Manipulación:
        - Cambiar elementos: simplemente uso `[]` para acceder a los elementos
        - Añadir elementos: lo agrego usando `+` y el elemento a añadir en corchetes
        - Eliminar elementos: uso `del[elemento]`

In [12]:
print(my_lista[0])
print(my_lista[-1])

print(my_lista[0:2])
print(my_lista[:3])
print(my_lista[-3:])

print(my_lista[0:])

my_lista[2] = 20
my_lista[0:2] =["ya", "cambié"]
print(my_lista)

print(my_lista + ["a lo seguro"])

del(my_lista[0])
print(my_lista)

hola
['años', 'y contanto']
['hola', 'tengo']
['hola', 'tengo', 10]
['tengo', 10, ['años', 'y contanto']]
['hola', 'tengo', 10, ['años', 'y contanto']]
['ya', 'cambié', 20, ['años', 'y contanto']]
['ya', 'cambié', 20, ['años', 'y contanto'], 'a lo seguro']
['cambié', 20, ['años', 'y contanto']]


### Operadores
- Booleanos se escriben con letras *and, or, not*
- Operadores `<,>,>=,<=,==,!=`

In [13]:
v1=True
v2=False
print(v1 and v2) 
print(v1 or v2)  
print(not v1)
print(5>6)

False
True
False
False


### Funciones

- Como en Matemáticas y se mandan llamar así `output = nombre_funcion(input)`
- `max()`, `round()`, `min()`

In [14]:
print(max([1, 378, 26, 8])), print(round(1.56)); print(round(1.56, 1))

378
2
1.6


> **EJERCICIO.** Crea un vector y normalízalo (i.e. que todos los valores queden entre 0 y 1). Después veremos otra manera de normalizar.

In [15]:
n = [10,15,25,46,78]

def normalize_lista(lista_normal):
    max_val = max(lista_normal)
    min_val = min(lista_normal)
    for i in range(len(lista_normal)):
        lista_normal[i] = (lista_normal[i]-min_val)/(max_val-min_val)
    return(lista_normal)

normalize_lista(n)

[0.0, 0.07352941176470588, 0.22058823529411764, 0.5294117647058824, 1.0]

### Métodos
- Todo en Python es objeto, tiene asociados métodos
- Los métodos son *funciones* de los objetos
- Se pueden usar cuando se instancia un *objeto* de la clase
- Se mandan llamar llamar usando `.` antes del objeto
- Métodos comunes de listas: 
    - `.index("Fer")` me da el índice de un elemento que quiera buscar en mi lista
    - `.count("cuentame")` me da las veces que el elemento aparece en mi lista
    - `.append("agrégame")` me permite añadir al final de mi lista un elemento
    - `.remove("elimíname")` me permite remover el primer elemento que cumple con el patrón dado
    - `.reverse` me pone el orden al revés
- Métodos comunes de strings:
    - `.capitalize()` me pone la primer letra de mi string en mayúscula
    - `.replace("ap", "rep")` me remplaza todas las ocurrencias de "ap" en mi lista por "rep"
    
- ¿Cómo saber qué métodos hay para un tipo de dato? -> usamos `?`

In [16]:
print(my_lista)
my_lista.index(20)

['cambié', 20, ['años', 'y contanto']]


1

In [17]:
my_lista

['cambié', 20, ['años', 'y contanto']]

> **EJERCICIO**. Crea una lista y aplica cada una de las funciones de arriba

### Paquetes
- Son como scripts
- Tienen definidas funciones y métodos
- Se tienen miles de paquetes. Los hay para ciencia de Datos y son los que veremos como:
    - **Numpy:** es el paquete fundamental para cómputo numérico, para manejar arreglos y matrices
    - **Matplotlib:** visualización en 2D
    - **Pandas:** manipulación de estructuras de datos con alto desempeño
    - **Scikit-learn:** machine learning
- Todos estos paquetes pertencen al ecosistema [SciPy](https://www.scipy.org/about.html), que quiere decir "Scientific Python", *Scientific Computing Tools for Python*
- Instalar:
    - pip, un manejador de paquetes. Ir [aquí](https://pip.readthedocs.io/en/stable/installing/) y bajar `get-pip.py`
    - Ejecutar `get-pip.py` en la terminal y así podemos usar `pip` para instalar paquetes
- Importar paquete: `import nombre_paquete` -> esto importa toda la funcionalidad del paquete
- Tenemos 3 opciones para importar:
    - Hay que dar alias al paquete para llamarlo `import numpy as np`
    - Si sólo queremos una función específica del paquete podemos usar: `from numpy import array`
    - Si queremos importar todo lo que tiene numpy hacemos `from numpy import *` -> esta opción nos permite no tener que llamar a cada método

In [18]:
import numpy as np

#array([10,30,40]) marca error porque el método del paquete se debe llamar

print("\n")
print("Imprimimos arreglo:")
print("\n")
print(np.array([10,30,40]))



Imprimimos arreglo:


[10 30 40]


In [19]:
from numpy import array

print("\n")
print("Si importamos 'array' igual nos imprime lo mismo")
print("\n")
print(array([10,30,40]))



Si importamos 'array' igual nos imprime lo mismo


[10 30 40]


## NumPy
- Las listas son potentes pero no es posible aplicar muchas operaciones matemáticas sobre ellas
- **NumPy** viene de "numeric Python"
- La arternativa a las listas es el "NumPy array", una librería de Python muy optimizada
- Se pueden hacer cálculos matemáticos sobre arreglos enteros fácil y rápidamente
- Desventaja vs listas: no se pueden guardar varios tipos de datos. Si se guardan diferentes entonces se hace *coerción*
- Sin embargo, NumPy es muy rápido justo gracias a que sólo guarda un tipo de dato
- Instalación: `pip install numpy`
- Se accesa igual que a las listas, usando `[]`
- Atributos importantes: 
    - `.size` para ver número de elementos
    - `.shape` para ver dimensión
    - `.dtype` para ver el tipo de datos que guarda
- Documentación de métodos para *arrays*: checar [aquí](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html)


In [20]:
import numpy as np
vec1 = np.array([1,2,3,4,5])

print("El vector construido es: ")
print(vec1)

print("\n")
print("Su número de elementos es:")
print(vec1.size)

print("\n")
print("Su dimensión es:")
print(vec1.shape)

print("\n")
print("Su tipo de datos es:")
print(vec1.dtype)

print("\n")
print("Podemos hacer operaciones aritméticas sobre él:")
print(vec1*3**2)

print("\n")
print("Sin embargo no es posible guardar varios tipos de datos:")
print(np.array([100, "Fer", False]))

print("\n")
print("Pero sí es posible sumar arrays: ")
print(np.array((30, 40, 55)) + np.array((20, 25, 16)))

print("\n")
print("Y accesar a sus componentes usando corchetes: ")
print(vec1[1])

print("\n")
print("Veamos qué entradas son mayores que 3")
print(vec1>3)

print("\n")
print("Y a qué elementos corresponden")
print(vec1[vec1>3])

El vector construido es: 
[1 2 3 4 5]


Su número de elementos es:
5


Su dimensión es:
(5,)


Su tipo de datos es:
int64


Podemos hacer operaciones aritméticas sobre él:
[ 9 18 27 36 45]


Sin embargo no es posible guardar varios tipos de datos:
['100' 'Fer' 'False']


Pero sí es posible sumar arrays: 
[50 65 71]


Y accesar a sus componentes usando corchetes: 
2


Veamos qué entradas son mayores que 3
[False False False  True  True]


Y a qué elementos corresponden
[4 5]


Operaciones útiles:


In [21]:
print("Imprimir los números pares: ")
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 0])

print("\n")
v1 = np.array([1,2,3,2,3,4,3,4,5,6])
print("v1 es: " + str(v1))
v2 = np.array([7,2,10,2,7,4,9,4,9,8])
print("v2 es: " + str(v2))
print("Posiciones en común: ")
print(np.where(v1 == v2))

print("\n")
print("Imprimir solo los números que están en cierto rango")
a = np.arange(20)
print(a)
print(a[(a >= 10) & (a <= 20)])

print("\n")
v1 = np.arange(10).reshape(2,-1)
v2 = np.repeat(1, 10).reshape(2,-1)
print("v1 es: ")
print(v1)
print("v2 es: " + "\n" + str(v2))
print("Stack dos vectores verticalmente: ")
print(np.vstack([v1, v2]))

print("Stack dos vectores horizontalmente: ")
print(np.hstack([v1, v2]))

print("\n")
print("Encontrar la intersección de dos vectores: ")

v1 = np.array([1,2,3,4,5,6])
print("v2 es: " + "\n" + str(v1))
v2 = np.array([6,7,10,2,7,4,9,4,9,8])
print("v2 es: " + "\n" + str(v2))
print("La intersección es: ")
print(np.intersect1d(v1,v2))

print("\n")
print("Diferencia de dos vectores: ")
print(np.setdiff1d(v1,v2))

      

Imprimir los números pares: 
[0 2 4 6 8]


v1 es: [1 2 3 2 3 4 3 4 5 6]
v2 es: [ 7  2 10  2  7  4  9  4  9  8]
Posiciones en común: 
(array([1, 3, 5, 7]),)


Imprimir solo los números que están en cierto rango
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]


v1 es: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
v2 es: 
[[1 1 1 1 1]
 [1 1 1 1 1]]
Stack dos vectores verticalmente: 
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Stack dos vectores horizontalmente: 
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Encontrar la intersección de dos vectores: 
v2 es: 
[1 2 3 4 5 6]
v2 es: 
[ 6  7 10  2  7  4  9  4  9  8]
La intersección es: 
[2 4 6]


Diferencia de dos vectores: 
[1 3 5]


> **EJERCICIO.** Calcula los siguientes vectores:


In [22]:
#Ahora remplaza los números pares por el valor -1000 (hint: igual que en R)

#Encuentra los números impares y reemplaza por -1

#Escribe un vector y normalízalo (i.e. que sus entradas queden entre 0 y 1). Hint: usa el método max() y el min()

#Ahora reemplaza todas las entradas que sean mayores o iguales que 0.5 por 1 y las que sean menores por -1

### 2d-dimensional arrays
- Se pueden crear con la misma sintaxis
- Con el método `.shape` se puede saber su dimensión
- No se pueden poner distintos tipos de datos
- Indexación se hace igual
- Es fácil indexar con `[m,n]` que con `[m][n]`

In [23]:
vec2d = np.array([[1, 2, 3],[4, 5, 6]])

print("El vector construido es: ")
print(vec2d)

print("\n")
print("Su dimensión es: ")
print(vec2d.shape)

El vector construido es: 
[[1 2 3]
 [4 5 6]]


Su dimensión es: 
(2, 3)


In [24]:
print("La primera entrada es: ")
print(vec2d[0])

print("\n")
print("El tercer elemento de la primera entrada es:")
print(vec2d[0][2])

print("\n")
print("El elemento segundo de las dos entradas son")
print(vec2d[ :, 1:2])

print("\n")
print("La segunda entrada es:")
print(vec2d[1, :])


La primera entrada es: 
[1 2 3]


El tercer elemento de la primera entrada es:
3


El elemento segundo de las dos entradas son
[[2]
 [5]]


La segunda entrada es:
[4 5 6]


## Basics de análisis de datos

- Igual que en R, es importante tener estadísticas de resumen: media, mediana, desviación estándar, correlaciones
- NumPy tiene muchas funciones predefinidas con este propósito
- Se puede generar cualquier variable aleatoria, ver [documentación](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)


In [25]:
muestra_normal = np.random.normal(0, 1, 10000)
muestra_exp = np.random.exponential(5, 10000)

vecsim = np.column_stack((muestra_normal, muestra_exp ))
print(type(vecsim))

print("\n")
print("El vector de normales y exponenciales simuladas es: ")

print("\n")
print(vecsim)

print("\n")
print("Resultados normal: ")
print("La media es " + str(np.mean(vecsim[:,0])))
print("La mediana es " + str(np.median(vecsim[:,0])))
print("La desviación estándar es " + str(np.std(vecsim[:,0])))


print("\n")
print("Resultados exponencial: ")
print("La media es " + str(np.mean(vecsim[:,1])))
print("La mediana es " + str(np.median(vecsim[:,1])))
print("La desviación estándar es " + str(np.std(vecsim[:,1])))

print(np.corrcoef(vecsim[0,:], vecsim[1,:]))

<class 'numpy.ndarray'>


El vector de normales y exponenciales simuladas es: 


[[-0.72339879  7.15817266]
 [ 0.66886912  2.85411789]
 [-1.51583656  2.95602252]
 ...
 [ 2.733624    5.18635079]
 [ 0.1245953   6.72972859]
 [ 0.69917057  7.3954382 ]]


Resultados normal: 
La media es 0.007774345237426792
La mediana es -0.001310746335947795
La desviación estándar es 0.9932986485504955


Resultados exponencial: 
La media es 4.980683435606724
La mediana es 3.414601045410401
La desviación estándar es 4.989981008006469
[[1. 1.]
 [1. 1.]]


In [26]:
print("El tamaño del arreglo es: ")
vecsim.shape

El tamaño del arreglo es: 


(10000, 2)

In [27]:
print("\n")
print("Y así se ve: ")
print("\n")
print(vecsim)




Y así se ve: 


[[-0.72339879  7.15817266]
 [ 0.66886912  2.85411789]
 [-1.51583656  2.95602252]
 ...
 [ 2.733624    5.18635079]
 [ 0.1245953   6.72972859]
 [ 0.69917057  7.3954382 ]]


In [28]:
print("La muestra de normales: ")
vecsim[:,0]


La muestra de normales: 


array([-0.72339879,  0.66886912, -1.51583656, ...,  2.733624  ,
        0.1245953 ,  0.69917057])

In [29]:
print("La muestra de exponenciales: ")
vecsim[:,1]


La muestra de exponenciales: 


array([7.15817266, 2.85411789, 2.95602252, ..., 5.18635079, 6.72972859,
       7.3954382 ])

## Visualización
- Existen varios paquetes para visualización, pero el estrella es `matplotlib`
- Permite hacer gráficos de líneas, de dispersión, histogramas
- Permite cambiar escala de los ejes `plt.xscale('log')`

### Gráfico de líneas

- Útil para series de tiempo
- Nos ayuda a ver tendencias

*Sintaxis:* `plt.plot(x, y)`

*Sintaxis:* Ejes con `plt.xlabel("eje x")`

*Sintaxis:* Ejes con `plt.ylabel("eje y")`

*Sintaxis:* Título con `plt.title("titulo")`


In [30]:
import matplotlib.pyplot as plt

plt.plot(vecsim[0:100, 0], vecsim[0:100, 1])
plt.xlabel("Simulaciones normales")
plt.ylabel("Simulaciones exponenciales")
plt.title("Simulaciones normales vs exponenciales")
plt.show()

<Figure size 640x480 with 1 Axes>

### Gráfico de dispersión

- Nos sirve para ver la relación entre dos variables numéricas
- Nos ayuda a ver una posible correlación 

*Sintaxis:* `plt.scatter(x, y)`

*Argumentos:* `scatter(x, y)`

*Sintaxis:* `plt.yticks([...])` o bien `plt.yticks([...], [names])` para poner un nombre a los ticks del eje y

*Sintaxis:* `plt.xticks([...])` o bien `plt.xticks([...], [names])` para poner un nombre a los ticks del eje x


*Sintaxis:* `range(inicio, fin, paso)`. Ojo, el fin es exclusivo, se detiene uno antes.

*Sintaxis: * `



In [ ]:
#help(plt.scatter)
plt.xscale('log')
plt.scatter(vecsim[0:100, 0], vecsim[0:100, 1])
plt.yticks([range(0, 10, 2)])
plt.yticks([0,2,4,6,8,10], ['0e','2e', '3e', '4e', '5e','6e'])
plt.show()

### Histograma

- Nos ayuda a ver distribución de UNA variable numérica

*Sintaxis:* `plt.hist(x, y)`

*Argumentos:* `hist(x, bins=None)`

- `plt.clf()` nos ayuda a limpiar para poder plotear otra cosa. Si no lo hacemos y ponemos enseguida otra gráfica, las encimará.

In [ ]:
print("\n")
print("Si no le damos el número de bins, el default es 10")


plt.hist(vecsim[0:100, 0])
plt.show()



In [ ]:

plt.clf()
print("\n")
print("Ahora le damos un número de bins de 20")

plt.hist(vecsim[0:100, 0], 20)
plt.show()



In [ ]:

plt.clf()
print("\n")
print("Ahora le damos un número de bins de 5")
plt.hist(vecsim[0:100, 0], 5)
plt.show()

In [ ]:
v1 = np.arange(10)
print(v1)

v1 = np.arange(10).reshape(2,-1)
print(v1)




## Estructuras de control

#### if-else

*Sintaxis:* 
    
    if [condition]:
          __execution if true__
    else:
          __execution if false__

In [ ]:
l1 = [1, 2, 3, 4, 5]
long_v1 = len(l1)
if long_v1 < 5:
    print ("El tamaño es menor que 5")
else:
    print("El tamaño es mayor o igual a 5")




#### for

*Sintaxis:* `Iterable` puede ser una lista o estructura de datos que permita iterar

    for i in [Python Iterable]:
        expression(i)

In [ ]:
print("Rutina que calcula la suma de los elementos pares de una lista")
lista=[]
for x in range(10):
    lista.append(x)

print("\n")
print("La lista es:")
print(lista)

suma=0

for x in lista:
    if x%2 == 0:
        suma += x

print("\n")
print("La suma es: " + str(suma))

#### while

*Sintaxis:* `Iterable` puede ser una lista o estrctura de datos que permita iterar

    while condition(i) :
        expression(i)

In [ ]:
i = 1
while i < 12:
  print(i)
  if i == 10:
    break
  i += 1

## Funciones

- Suprogramas para llevar a cabo tareas específicas
- Tres tipos de funciones en Python:
    - **Predefinidas:** `print()`, `help()`, `min()`. Ver [más](https://docs.python.org/3/library/functions.html)
    - **Definidas por el usuario** (User defined functions, aká UDF), creadas con `def`
    - **Anónimas** (no son creadas con `def`), también llamadas *funciones lambda*

#### Función vs método
- Los métodos que vimos son casos especiales de funciones que forman parte de una clase
- No toda función es un método
 

In [ ]:
#La función "suma":
def suma(a,b):
  return a + b
  
#La clase "sumar" con el método "sumando":
class sumar(object):
  def sumando(self, a, b):
    self.contents = a + b
    return self.contents 

#Usamos la función suma:
print(suma(100, 50))

#Instanciamos un objeto de la clase "sumar" y luego usamos su método "sumando"
obj_sumar = sumar()
print(obj_sumar.sumando(100,50))

##### Parámetros vs argumentos

- Los *argumentos* son las variables/nombres declarados de las que dependen las funciones y los métodos
- Los *parámetros* son los los *valores específicos* de los *argumentos*

> **Ejercicio.** ¿Cuáles son los *argumentos* y parámetros de la función *suma*? ¿Cuáles son los *argumentos* y parámetros de la clase *sumar* y el método *sumando*?

- El primer argumento de toda *clase* hará referencia a una *instancia* de la misma
- Por convención, a este argumento en Python se le llama `self`
- En en caso de la *clase sumar* entonces `self` se refiere a esta instanciación
- Entonces cuando se invoca el método *sumando*, el argumento `self` se convierte en un *parámetro* pasado de manera *implícita* 

#### Funciones definidas por el usuario (UDF)

Necesitamos cuatro ingredientes sintácticos para crear una *UDF*:

1. Se usa la palabra reservada `def` para decir que haremos una función, seguida del nombre de la función

2. Después los parámetros se indican dentro de paréntesis y al final se ponen `:`

3. Posteriormente se pone el código a ejecutar

4. Se usa al final la declaración `return` con lo que queremos que regrese. Se pueden regresar varias cosas, no sólo una. En R no podíamos hacer esto (tendríamos que regresar una lista con todos los returns)


> **Ejercicio.** Define una función que imprima tu nombre e incluye el `return`  al final sin que regrese nada. ¿Qué pasa si quitas el `return`? ¿Cuál crees que sea la ventaja de tener un `return`, aunque sea una impresión?

Con la función `input("texto que le pedimos al usuario")` le pedimos algo al usuario:

In [ ]:
#name = str(input("Dame tu nombre: "))

> **Ejercicio.** Escribe una función que le pida su nombre y edad al usuario y que si el usuario se los da, imprima algo como "Hola Fer, ya sé que tienes 20 años, ¡muy buenos días!". Y si no, imprima "Hola anónimo, muy buenos días"



In [ ]:
#def saludo():
#  nombre = str(input("Dame tu nombre: "))
#  edad = str(input("Dame tu edad: "))
#  if nombre:
#    print ("Hola " + str(nombre) + ", ya sé que tienes " + str(edad) + " años" + " ¡muy buenos días!")
#  else:
#    print("Hello World") 
#  return

#saludo()

Ahora veamos un ejemplo en donde regresamos varias cosas

##### Docstrings

- Sirven para explicar qué hace la función, qué recibe, qué arroja y cualquier cosa que se quiera añadir de documentación sobre la función

- Para ver ejemplos más grandes de *docstrings* de mismas librerías ver [aquí](https://github.com/scikit-learn/scikit-learn/tree/master/sklearn)

In [ ]:
def suma(a,b):
""" 
Definition:Suma dos numeros

Input: dos numeros

Output:
Dos numeros y su suma
"""
    res = a + b
    return(res, a, b)


res1, a, b = suma(50, 100)
print(res1)

##### Tipos de argumentos
- **Default:** toman un valor por default pero se pueden modificar posteriormente
- **Requeridos:** es obligatorio mandarlos cuando se llama la función
- **Keyword:** son cuando al llamar la función, los asignamos usando el nombre del argumento original de la función. Cuando usamos esta modalidad, podemos cambiar el orden de llamada de los argumentos.
- **Número variable de argumentos:** Se indican con un `*` antes de un nombre de variable que escojamos, que indicará todos los argumentos variables. Se usan cuando no sabemos cuántos argumentos se usarán.

> **Ejercicio.** De la siguiente función, ¿qué argumentos son por default, cuáles son requeridos y cuáles son con keywords?

In [ ]:
def suma2(a,b = 10):
  return a + b

#Llamamos a suma con un argumento
print(suma2(a=5))

#Llamamos a suma con dos argumentos
print(suma2(a=5, b=8))

In [ ]:
#Argumentos variables
def suma3(*varvars):
  return sum(varvars)

suma3(10,20,30)

##### Variables globales vs locales

- Las que se definen dentro de las funciones que tienen un alcance *local*, es decir, no pueden ser accesadas desde fuera
- Las que se definen fuera de las funciones tienen un alcance *global*, pueden ser accesadas en cualquier parte del programa

#### Funciones anónimas

- Se llaman *anónimas* porque no se declaran con el keyword `def`; de hecho no tienen nombre (son *nameless*)
- Se declaran usando el keyword `lambda` con la siguiente sintaxis: `lambda arguments: expression`
- Se usan cuando se requiere de una función por un período corto de tiempo y que se crea en tiempo de ejecución
- También se usa como argumento para otras funciones
- Se usa con otras funciones como `filter()`, `map()`, y `reduce()`
- `MapReduce` es un modelo de programación para hacer cómputo paralelo y distribuido en conjuntos muy grandes de datos, por eso se usa mucho para hacer procesar Big Data
- Hay bibliotecas de MapReduce en C++, Python y Java e implementaciones de frameworks como el de Apache Hadoop
- Consiste de un método de *Map* (mapeo) que hace algún *filtrado* u *ordenado* de los datos y posteriormente un método de *Reduce*, que hace una operación que hace algún resumen
- No todos los datos se pueden procesar usando *MapReduce*
- Se requiere hacer *marshalling* de los servidores, correr tareas en *paralelo*, manejar la *comunicación* y la *transmisión* de los datos en el sistema, así como proveer soporte de sistemas distribuidos como *tolerancia a fallos* y *redundancia*

In [ ]:
potencia = lambda x: x**2
res = potencia(4)
print(res)

> **Ejercicio.** Escribe la versión `lambda`de la función suma que hicimos.

- Un ejemplo usando las funciones `filter()`, `map()` y `reduce()`
- `reduce()` se tiene que importar: `from functools import reduce`



In [ ]:
from functools import reduce

#filter()
lista1 = range(0,10)
lista2 = list(filter(lambda x: (x%2 == 0) , lista1))
print(lista2)

#map()
lista3 = range(0,10)
lista4 = list(map(lambda x: x + 1 , lista3))
print(lista4)

#reduce()
lista5 = reduce(lambda x, y: x+y, lista3)
print(lista5)

### Diccionarios

- Útiles para unir keys a valores de manera eficiente
- Se indican con `{}`


In [ ]:
nombres = ['maria', 'pepe', 'tina', 'alberto']
segmento = ['bajo', 'bajo', 'alto', 'medio']

i = nombres.index("alberto")

print(segmento[i])

In [ ]:
print("Es mejor escribirlo como diccionario: ")
nomina = {
   "maria":"bajo",
   "pepe":"bajo",
   "tina":"alto",
   "alberto":"medio" 
}
print(nomina)

In [ ]:
print("Puedo imprimir las llaves: ")
print(nomina.keys())

print("\n")
print("También puedo imprimir el valor de Maria: ")
print(nomina["maria"])

## Data frames

- `Pandas` es un paquete popular para ciencia de datos
- Ofrece estructuras de datos orientadas a este fin
- Facilita la manipulación y análisis de datos
- Fueron hechos sobre la librería de `Numpy`, que guarda los datos en *arrays*
- Se crean desde la librería de `Pandas`
- Pueden contener lo siguiente:
    - Un `ndarray` de Numpy (una o dos dimensiones): puedes agregar índices o nombres de filas y columnas (metadata). Por eso se les llama también "Numpy arrays diccionariados"
    - Un `Dataframe` de Pandas: son como los dataframes de R, i.e. puedo guardar varios tipos de datos
    - Una `serie` de Pandas
    - Páneles: contenedores de datos en 3D (esto no lo vimos en R)
- Entonces, igual que en R, podemos organizar las estructuras de datos por su  *dimensión* y *contenido*:



<img src="numpyvspandas.png"  width="500" height="300">

- Vamos a importar la librería de Pandas como "pd"

### Creación de dataframes

**Opción 1:** Convertir desde otra estructura de datos (listas o Numpy arrays)

*Sintaxis:* `pd.DataFrame(data = , index = , columns = )`
   - `data`: selecciono los datos
   - `index`: selecciono las filas
   - `columns`: selecciono las columnas
   
También podemos conocer la dimensión con `shape()` o con `len()`

In [ ]:
import pandas as pd
ej = np.array([['','col1','col2'],
                ['fila1',10,2],
                ['fila2',30,5], ['fila3',6,7]])

print("Imprimo array de Numpy:")
print(ej)

print("\n")
print("Tipo de dato: " + str(type(ej)))

print("\n")
print("Imprimo dataframe de Pandas:")
array_to_df = pd.DataFrame(data = ej[1:,1:],
                  index = ej[1:,0],
                  columns = ej[0,1:])

print(array_to_df)

print("\n")
print("Tipo de dato: " + str(type(array_to_df)))

print("\n")
print("La dimensión es: ")
print(array_to_df.shape)

print("\n")
print("El número de filas es: ")
print(len(array_to_df.index))


Ejemplo de cuando los datos son una lista:

In [ ]:
df_ex = pd.DataFrame(data=[10,20,30,40], index=range(0,4), columns=['val'])
print(df_ex)

print("\n")

#nombres de columnas:
print(list(df_ex.columns))

print("\n")

#o bien:
list(df_ex.columns.values)

> **EJERCICIO.** Crea e imprime un *dataframe* de Pandas de tamaño 10 de una variable aleatoria uniforme en (0,10000) y de una variable Poisson con parámetro 5.

In [ ]:
#Solución
v1 = np.random.uniform(0, 10000, 10)
print(v1)
print(v1.shape)
v2 = np.random.poisson(5, 10)
#print(np.vstack((v1, v2)))
#print(np.concatenate((v1, v2)).shape)
#df_ex = pd.DataFrame(data=np.column_stack((v1, v2)), index=range(0,9), columns=['id'])
#print(df_ex)



**Opción 2:** Crear desde cero

In [ ]:
type(np.random.normal(0, 1, 10000))

In [ ]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))
array([1, 2, 3, 2, 3, 4])
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))
print(type(np.hstack((a,b))))
print(np.hstack((a,b)))

In [ ]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))
print(type(np.column_stack((a,b))))
print(np.column_stack((a,b)))

- También podemos crear un Dataframe vacío:

In [ ]:
df = pd.DataFrame(np.nan, index=range(0,8), columns=['A'])
print(df)

print("\n")
print("El tipo de dato es: ")
print(type(np.nan))

print("\n")
print("Si ahora le queremos dar un tipo distinto al float: ")
df = pd.DataFrame(index=range(0,8), columns=['c1'], dtype='int')
print(df)
print(type(df))

### Operaciones en dataframes

- Parecido a lo que podíamos hacer con el paquete `dplyr` en R
- Sintaxis casi igual a los Numpy arrays
- Para ver los primeros 5 registros se hace `dataframe.head()`

In [ ]:
#### Seleccionar elementos

In [ ]:
print(array_to_df)

print("\n")
print("El elemento en la posición (0,0) es: ")
# Con `iloc[]`
print(array_to_df.iloc[0][0])
print("La primer fila es:")
print(array_to_df.iloc[0])


print("\n")
print("El elemento en la columna y fila (fila1,col1) es: ")
# Con `loc[]`
print(array_to_df.loc['fila1']['col1'])
print("La primer fila es:")
print(array_to_df.loc['fila1'])



print("\n")
print("Agregamos una columna 3 con el índice: ")
array_to_df['col3'] = array_to_df.index
print(array_to_df)

df_reset = array_to_df.reset_index(drop=True)

print(df_reset)

#### Agregar filas y columnas
- `df.loc[nombre_fila]`
- `df.loc[, nombre_columna]`

In [ ]:
print("Agregando columnas:")
print(array_to_df)
print("\n")
array_to_df.loc[:, "col5"] = pd.Series(['5', '6', '7'], index=array_to_df.index)
print(array_to_df)

print("\n")
array_to_df.loc[:, 6] = pd.Series(['9', '10', '11'], index=array_to_df.index)
print(array_to_df)

print("\n")
print("Agregando filas:")
array_to_df.loc[4] = [10, 11, 12, 13, 14]
print(array_to_df)
print("\n")
array_to_df.loc["fila5"] = [10, 11, 12, 13, 14]
print(array_to_df)

#### Eliminar filas o columnas, cambiar nombres de índices
- Eliminar columnas/filas: `df.drop('column/row_name', axis=, inplace=)`
- `axis` me dice si quito filas o columnas
- `inplace=True` me elimina la columna sin necesidad de reasignar el DataFrame
- Cambiar nombres de índices: `df.rename(columns=newcols, inplace=True)`


In [ ]:
print(array_to_df)

print("\n")
print("Elimino primer columna")
array_to_df.drop("col1", axis=1, inplace=True)
print(array_to_df)

print("\n")
print("Elimino primer fila")
array_to_df.drop("fila1", axis=0, inplace=True)
print(array_to_df)

print("\n")
print("Cambio nombres de filas")
nuevcols=newcols = { 
    'col2': 'var1', 
    'col3': 'var2',
    'col5': 'var3',
    6: 'var4'
}
array_to_df.rename(columns=nuevcols, inplace=True)
print(array_to_df)

#### Recodificar data
- Reemplazar una data por otra: `replace([to_replace],[value])`
- Puedo usar el parámetro `dict` para decirle de una vez, por columna qué reemplazos debe hacer
- Ver [documentación](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.replace.html#pandas.DataFrame.replace) para ver parámetros y opciones
- Cambio los "fila" por valores: `

In [ ]:
array_to_df.replace(['fila2', 'fila3'], [2,3])

#### Pivot tables

- Son como las de Excel
- Ver la [documentación aquí](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pivot_table.html#pandas.DataFrame.pivot_table)
- Ejemplo tomado de [aquí](http://pbpython.com/pandas-pivot-table-explained.html)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_excel("sales.xlsx")
df.head()

Columnas que queremos ver, por ejemplo *Name*:

In [ ]:
df["Status"] = df["Status"].astype("category")

pd.pivot_table(df,index=["Name"])

Podemos sumar todos los precios agregando una función a `aggfunc`. Entonces `aggfunc` se aplica sobre los `values`:

In [ ]:

pd.pivot_table(df,index=["Manager","Rep"],values=["Price"],aggfunc=np.sum)

También podemos pasarle varias funciones para que haga varios resúmenes:

In [ ]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"],aggfunc=[np.mean,len])

Podemos usar también *columnas* para darle un nivel extra de segmentación a nuestros datos:

In [ ]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"],
               columns=["Product"],aggfunc=[np.sum])

También podemos eliminar los Nas:

In [ ]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"],
               columns=["Product"],aggfunc=[np.sum],fill_value=0)

Finalmente también podríamos agregar un nivel más en `value`:

In [ ]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price","Quantity"],
               columns=["Product"],aggfunc=[np.sum],fill_value=0)

Para agregar los totales hacemos `margins=True`

In [ ]:
pd.pivot_table(df,index=["Manager","Rep","Product"],
               values=["Price","Quantity"],
               aggfunc=[np.sum,np.mean],fill_value=0,margins=True)

Un pequeño resumen:

<img src="pivot.png"  width="400" height="200">

#### Tablas cruzadas

- Sirven para visualizar la relación entre dos variables categóricas
- Parte del análisis exploratorio de datos, cuando sospechamos que dos variables categóricas están relacionadas
- Se hacen con el comando `pd.crosstab(df["Var1"],df["Var2"],margins=True)`

#### Aplicar función a filas o columnas

- `dataframe.apply(funcion, axis=0/1)` me permite aplicar una función (predefinida o hecha por mí) a los elementos de mi dataframe, ya sea por fila o columna

In [ ]:
df2 = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]), columns=['A', 'B', 'C'])
df2.describe()

#### Iterar el Dataframe

In [ ]:
df2 = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]), columns=['A', 'B', 'C'])
print(df2)

print("\n")
print("Recorro dataframe: ")

for index, row in df2.iterrows() :
    print(row['A'], row['B'])

#### Ordenar el dataframe
- Muy parecido a R
- *Sintaxis:* df.sort_values(['var1','var2'], ascending=False)

In [ ]:
print("Creamos muestra de normal y el dataframe:")
muestra_norm = np.random.normal(10, 20, 50)
df_norm = pd.DataFrame(data = muestra_norm, index = range(0, 50), columns = ["valor"])
print(df_norm.head(10))

print("\n")
print("Ordenamos:")
muestra_sorted = df_norm.sort_values(['valor'], ascending=False)
print(muestra_sorted.head(10))



### Visualización

- A través de `Pandas`, es posible hacer gráficos de un dataframe de una manera más sencilla que usando directamente `matplotlib`


In [ ]:
muestra_exp = np.random.exponential(5, 100)
print(muestra_exp.shape)

print("\n")
print("Creamos dataframe de un array")
mexp = pd.DataFrame(data = muestra_exp, index = range(0, 100), columns = ["valor"])
print(mexp)

print("\n")
print("Graficamos")
mexp['valor'].hist(bins=10)

In [ ]:
print("\n")
print("Ahora grafiquemos el diagrama de caja y brazos: ")
mexp.boxplot(column='valor')

### Algo de estadística en dataframes

#### Descriptivos básicos
-  `dataframe.describe()` me da el número de observaciones, la media, la desviación estándar, el mínimo, el máximo y los cuartiles
- Tabla comparativa vs R:


| R               | Pandas           | 
| ----------------------- |:------------------------------------ | 
| summary(df)     | df.describe()    |
| head(df)        | df.head()        |
| dim(df)         | df.shape()       |
| str()           |df.dtypes / df.info()    |         

#### Manejo de NA's
- `isnull()`  es una función booleana que checa si una observación es nula
- Uso: `df['nombre_col'].isnull().sum()` me dice cuántos valores nulos tengo en una columna
- Vimos que en general es complicado manejar los NAs
- Vimos que a menos que los NAs representen una cantidad considerable, los vamos a eliminar


In [ ]:
print("Cuento cuántos Nas tengo: ")
df3 = pd.DataFrame(np.nan, index=range(0,10), columns=['A'])
n_nas = df3['A'].isnull().sum()
print(n_nas)

print("\n")
print("Para eficientarlo, ahora hagamos una función que haga eso")
def num_nulos(x):
  return x.isnull().sum()

print("Número de Nas por fila: ")
print("Nas por fila:")
print(df3.apply(num_nulos, axis=1))

print("\n")
print("Número de Nas por columna: ")
print(df3.apply(num_nulos, axis=0))

- Si no los vamos a eliminar, podemos sustituir los cuantitativos con la *media*, la *mediana*, la *moda* usando `fillna`:
    - Moda: `from scipy.stats import mode` -> `mode(df['Numvar'])
    - Comando completo: `df['Numvar'].fillna(mode(data['Numvar']).mode[0], inplace=True)

In [ ]:
print("Sustituyo Nas con otro valor: ")
df3['A'].fillna(0, inplace=True)
print(df3)

print("\n")
print("Verifico que ya no estén. La suma de nulos es: ")
print(df3.apply(num_nulos, axis=0))

### Importación de datos

- La mayoría de las veces usaremos **numpy** o **pandas** para importar 

#### Archivos de texto plano

- Con `numpy`

In [ ]:
import numpy as np
import pandas as pd

print("Este archivo tiene un solo tipo de datos: ")
filename = ‘mnist.txt’
data = np.loadtxt(filename, delimiter=',', skiprows=2, usecols=[0,2], dtype=str) 
print("\n")

print("Este archivo tiene varios tipos de datos: ")
filename = 'titanic.csv'
data = np.genfromtxt(filename, delimiter=',', names=True, dtype=None)

- Con `pandas`

In [ ]:
filename = 'winequality-red.csv'
colnom = ["acreditado", "sexo", "edad", "año"]
data = pd.read_csv(filename, nrows=5, header=None, sep='\t', comment='#', na_values= '-1', names = colnom) 

#### Excel 

In [ ]:
file = 'urbanpop.xlsx'
data = pd.ExcelFile(file)
df_sheet2 = data.parse('1960-1966', skiprows=[0], names=['Country', 'AAM: War(2002)'])
df_sheet1 = data.parse(0, parse_cols=[0], skiprows=[0], names=['Country'])
data.sheet_names

#### SAS

In [ ]:
from sas7bdat import SAS7BDAT
with SAS7BDAT('urbanpop.sas7bdat') as file:
df_sas = file.to_data_frame()

In [ ]:

#### Plain text
- *Sintaxis:* `pd.read_csv("file.csv", index_col=)`


In [ ]:
#Como csv
import pandas as pd
df2.to_csv('midataframe.csv', sep='\t', encoding='utf-8', header=False)

print("\n")
#Como excel
escritura = pd.ExcelWriter('midataframe.xlsx')
df.to_excel(escritura, 'DataFrame')
escritura.save()


#### Escribir dataframe en un archivo

- Como [csv](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)

- Como [excel](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_excel.html)

## EJERCICIO para entregar (1era parte)

1. Importa con la librería de pandas, como csv, los datos que vienen aquí: 

    - https://s3-ap-southeast-1.amazonaws.com/av-datahack-datacamp/train.csv y llámalo train.set
    
    - https://s3-ap-southeast-1.amazonaws.com/av-datahack-datacamp/test.csv y llámalo test.set

2. Revisa [este sitio](https://datahack.analyticsvidhya.com/contest/practice-problem-loan-prediction-iii/) para que entiendas el reto.Busca la documentación que viene sobre el dataset para llenar la misma tabla que llenaste para R, en donde venga la descripción, el tipo de variable, los rangos.
    
3. ¿Cuántas observaciones se tienen en cada dataset? ¿Cuántas columnas (puedes usar `dataframe.columns`)? ¿Cuáles son los primeros 5 registros?

4. Observa cuántos Nas tienes por columna y por fila (usa la función que vimos para hacerlo para todas las columnas/filas de una vez). Elimina las filas en donde haya valores nulos.

5. Recodifica a 0-1 las variables categóricas que estén siendo tratadas como strings. Usa la función `replace` que vimos, con un diccionario para hacer esto.

6. Da un resumen de la media, la mediana, desviación estándar, mínimo, máximo de las variables. Adicionalmente usa `df[col_name].value_counts()` para saber cuántas observaciones se tienen para las variables categóricas.

7. Para las variables categóricas, usa una `crosstab` para saber si se les da más créditos a las mujeres que a los hombres.  Usa otra `crosstab` para saber si el hecho de tener historial crediticio hace que sea más fácil que te aprueben un crédito. ¿Cuáles son tus conclusiones?
    **BONUS:** Investiga cómo poner porcentajes en estas tabla en vez de números.
    
8. Haz un histograma para el ingreso de la persona y otro para la cantidad prestada. ¿Qué observas?

9. Haz un boxplot para la cantidad del préstamo según el historial crediticio de la persona. ¿Hay diferencias en la cantidad prestada dependiendo si tiene historial o no? Repite el mismo boxplot pero ahora según el sexo. ¿Hay diferencias?



# Referencias

- Tidy Data. *Hadley Wickham*. Journal of Statistical Software. August 2014, Volume 59, Issue 10. https://www.jstatsoft.org/article/view/v059i10

- Datacamp. Courses for Data Scientists, 2018. https://www.datacamp.com/

- https://scikit-learn.org/stable/